// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/order.proto

package orderpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	OrderId              string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol               string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Volume               float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Side                 string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	OrderType            string                 `protobuf:"bytes,5,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	LimitPrice           float64                `protobuf:"fixed64,6,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafe5ffedbc3a278, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Order) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Order) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *Order) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *Order) GetLimitPrice() float64 {
	if m != nil {
		return m.LimitPrice
	}
	return 0
}

func (m *Order) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type PlaceOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafe5ffedbc3a278, []int{1}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type PlaceOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderResponse) Reset()         { *m = PlaceOrderResponse{} }
func (m *PlaceOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderResponse) ProtoMessage()    {}
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eafe5ffedbc3a278, []int{2}
}

func (m *PlaceOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderResponse.Unmarshal(m, b)
}
func (m *PlaceOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderResponse.Marshal(b, m, deterministic)
}
func (m *PlaceOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderResponse.Merge(m, src)
}
func (m *PlaceOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderResponse.Size(m)
}
func (m *PlaceOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderResponse proto.InternalMessageInfo

func (m *PlaceOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*PlaceOrderRequest)(nil), "order.PlaceOrderRequest")
	proto.RegisterType((*PlaceOrderResponse)(nil), "order.PlaceOrderResponse")
}

func init() {
	proto.RegisterFile("proto/v1/order.proto", fileDescriptor_eafe5ffedbc3a278)
}

var fileDescriptor_eafe5ffedbc3a278 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x3b, 0x4f, 0xc3, 0x30,
	0x10, 0x96, 0xa1, 0x0f, 0x72, 0xed, 0x82, 0x85, 0x90, 0x5b, 0x09, 0xb5, 0xca, 0xd4, 0x29, 0x11,
	0x65, 0x00, 0xc6, 0xb2, 0x31, 0x51, 0x42, 0x27, 0x96, 0x2a, 0x8f, 0xa3, 0xb2, 0x94, 0x60, 0x63,
	0x3b, 0x91, 0xf2, 0x73, 0xf9, 0x27, 0x28, 0xe7, 0x54, 0x20, 0xc1, 0xc0, 0x96, 0xef, 0x75, 0xb9,
	0xef, 0x0c, 0x17, 0xda, 0x28, 0xa7, 0xe2, 0xe6, 0x3a, 0x56, 0xa6, 0x40, 0x13, 0x11, 0xe4, 0x43,
	0x02, 0xf3, 0xc5, 0x41, 0xa9, 0x43, 0x89, 0x31, 0x91, 0x59, 0xfd, 0x16, 0x3b, 0x59, 0xa1, 0x75,
	0x69, 0xa5, 0xbd, 0x2f, 0xfc, 0x64, 0x30, 0x7c, 0xea, 0xac, 0x7c, 0x06, 0x67, 0x94, 0xd9, 0xcb,
	0x42, 0xb0, 0x25, 0x5b, 0x05, 0xc9, 0x98, 0xf0, 0x63, 0xc1, 0x2f, 0x61, 0x64, 0xdb, 0x2a, 0x53,
	0xa5, 0x38, 0x21, 0xa1, 0x47, 0x1d, 0xdf, 0xa8, 0xb2, 0xae, 0x50, 0x9c, 0x2e, 0xd9, 0x8a, 0x25,
	0x3d, 0xe2, 0x1c, 0x06, 0x56, 0x16, 0x28, 0x06, 0xe4, 0xa6, 0x6f, 0x7e, 0x05, 0xe0, 0xc7, 0xbb,
	0x56, 0xa3, 0x18, 0x92, 0x12, 0x10, 0xb3, 0x6b, 0x35, 0xf2, 0x05, 0x4c, 0x4a, 0x59, 0x49, 0xb7,
	0xd7, 0x46, 0xe6, 0x28, 0x46, 0x34, 0x0f, 0x88, 0xda, 0x76, 0x0c, 0xbf, 0x07, 0xc8, 0x0d, 0xa6,
	0x0e, 0x8b, 0x7d, 0xea, 0xc4, 0x78, 0xc9, 0x56, 0x93, 0xf5, 0x3c, 0xf2, 0xf5, 0xa2, 0x63, 0xbd,
	0x68, 0x77, 0xac, 0x97, 0x04, 0xbd, 0x7b, 0xe3, 0xc2, 0x5b, 0x38, 0xdf, 0x96, 0x69, 0x8e, 0xd4,
	0x33, 0xc1, 0x8f, 0x1a, 0xad, 0xe3, 0x21, 0xf8, 0x13, 0x51, 0xd7, 0xc9, 0x7a, 0x1a, 0xf9, 0xeb,
	0x79, 0x8f, 0x97, 0xc2, 0x3b, 0xe0, 0x3f, 0x83, 0x56, 0xab, 0x77, 0x8b, 0xff, 0x49, 0xae, 0x9f,
	0x61, 0x4a, 0xf8, 0x05, 0x4d, 0xd3, 0x6d, 0xbf, 0x01, 0xf8, 0x9e, 0xc4, 0x45, 0x1f, 0xf9, 0xb5,
	0xd5, 0x7c, 0xf6, 0x87, 0xe2, 0x7f, 0xfb, 0x10, 0xbc, 0xfa, 0xf7, 0xd0, 0x59, 0x36, 0xa2, 0xbe,
	0x37, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0x8b, 0x2c, 0x37, 0xfb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	out := new(PlaceOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/PlaceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/PlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _OrderService_PlaceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/order.proto",
}
